# Numpy

In [183]:
import numpy as np  # import numpy

# Creating Arrays (Using `array()` function)

We can create 0-Dimensional (a single value), 1-Dimensional, 2-Dimensional, 3-Dimensional, ..., multi-dimensional arrays in numpy!

In [184]:
a = np.array(25)  # Create 0-D array with value 25
print(a)

25


In [185]:
a = np.array([25, 24, 23])  # Create 1-D array with values 25, 24, 23
print(a)

[25 24 23]


In [186]:
# Create 2-D array
a = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
print(a)

[[1 2 3]
 [4 5 6]]


In [187]:
a[0][2]

3

In [213]:
# Create 3-D array
a = np.array([
    [
        [1, 2, 3],
        [4, 5, 6]
    ],
    [
        [25, 30, 35],
        [60, 70, 80]
    ]
])
print(a)
a[1][0][1]

[[[ 1  2  3]
  [ 4  5  6]]

 [[25 30 35]
  [60 70 80]]]


30

### Initializing array with `zeros()`, `full()`, `ones()`, `eye()`, etc.

In [189]:
b = np.zeros(3)
print(b)

[0. 0. 0.]


In [190]:
b = np.zeros([2, 3], dtype=int)  # With specific size/dimension
print(b)

[[0 0 0]
 [0 0 0]]


In [191]:
b = np.full([2, 3, 4], 10)
print(b)

[[[10 10 10 10]
  [10 10 10 10]
  [10 10 10 10]]

 [[10 10 10 10]
  [10 10 10 10]
  [10 10 10 10]]]


In [192]:
b = np.ones(3)
print(b)

b = np.ones([3, 2])
print(b)

[1. 1. 1.]
[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [193]:
b = np.eye(3)  # Create a 3x3 identity matrix
print(b)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


### Initializing arrays with ranges

`arange()`, `linspace()`, `logspace()`, etc.

In [194]:
a = np.arange(0, 10, 2)  # start, stop (exclusive), step
a

array([0, 2, 4, 6, 8])

In [195]:
a = np.arange(0, 10, 2, dtype=float)  # start, stop (exclusive), step
a

array([0., 2., 4., 6., 8.])

In [196]:
# linspace(start, stop, num)
# start: starting value of the array
# stop: ending value of the array (inclusive)
# num: no. of values in the array
# Keeps num-2 equal checkpoints in range(start, stop+1)
a = np.linspace(10, 100, 10)
print(a)

[ 10.  20.  30.  40.  50.  60.  70.  80.  90. 100.]


In [197]:
a = np.logspace(10, 100, 10)  # gives log base 10 values of linspace(start, stop, num)
print(a)

a = np.logspace(10, 100, 10, base=2)  # gives log base 2 values of linspace(start, stop, num)
print(a)

[1.e+010 1.e+020 1.e+030 1.e+040 1.e+050 1.e+060 1.e+070 1.e+080 1.e+090
 1.e+100]
[1.02400000e+03 1.04857600e+06 1.07374182e+09 1.09951163e+12
 1.12589991e+15 1.15292150e+18 1.18059162e+21 1.20892582e+24
 1.23794004e+27 1.26765060e+30]


# Array properties: `size`, `shape`, `dtype`, etc

In [198]:
a = np.array([10, 15, 25, 67, 21])
print(a.size)
print(np.size(a))

5
5


In [199]:
print(a.shape)
print(np.shape(a))

a = np.zeros([2, 3])
a.shape

(5,)
(5,)


(2, 3)

In [200]:
print(a.dtype)

float64


# Array operations
slicing, indexing, `copy()`, `view()`, `sort()`, `reshape()`, `append()`, `insert()`, `delete()`, `concatenate()`, `stack()`, etc.

In [201]:
b = np.copy(a)  # deep copy
b

array([[0., 0., 0.],
       [0., 0., 0.]])

In [202]:
c = b.view()  # shallow copy
c

array([[0., 0., 0.],
       [0., 0., 0.]])

In [203]:
a = np.array([5, 4, 3, 2, 1])
# np.sort(a)
a.sort()
a

array([1, 2, 3, 4, 5])

In [204]:
a = np.array([[5, 40, 3, 20, 1], [-2, 4, 30, 10, 3]])
a.sort()
a

array([[ 1,  3,  5, 20, 40],
       [-2,  3,  4, 10, 30]])

In [205]:
a = np.array([[5, 40, 3, 20, 1], [-2, 4, 30, 10, 3]])
a.sort(axis=0)  # axis = 0 for column wise sorting and 1 for row wise sorting
a

array([[-2,  4,  3, 10,  1],
       [ 5, 40, 30, 20,  3]])

In [206]:
a = np.arange(10, 101, 10)
a.reshape(2, 5)  # 2 * 5 must be size of array (10)

array([[ 10,  20,  30,  40,  50],
       [ 60,  70,  80,  90, 100]])

In [212]:
a = np.array([1, 2])
b = np.array([[3, 4], [5, 6]])
np.append(a, b)  # Flattens a bigger dimension array to add

array([1, 2, 3, 4, 5, 6])

In [208]:
np.insert(a, 2, [3, 4])  # (arr, index, value/values)

array([1, 2, 3, 4])

In [209]:
np.delete(a, 1)  # (arr, index)

array([1])

In [ ]:
b = np.array([2, 3])
np.concatenate((a, b))  # It cannot flatten a bigger dimension array to add. So, both the arrays must be of same shape

array([1, 2, 2, 3])

In [ ]:
a = np.array([[1, 2], [7, 8]])
b = np.array([[3, 4],[5, 6]])
np.concatenate((a, b), axis=1)  # Column wise concatenation of 2-D arrays

array([[1, 2, 3, 4],
       [7, 8, 5, 6]])

# ***For remembering axis values***

* `axis = 0` for column-wise (horizontal-wise)
* `axis = 1` for row-wise (vertical-wise)